MySQL:
  Enabled: false
  AutoReconnect: false
  Host: 127.0.0.1
  Database: database
  Username: LimboAuth
  Password: '12345'
  Port: 3306
Commands-On-Auth: "p:/server survival;c:/server %player% survival"